# Python & numpy review

- 유용한 강좌
- [CS231 python tutorial 한글번역](http://aikorea.org/cs231n/python-numpy-tutorial/)
- 
[Scipy-lectures](https://scipy-lectures.org/)
    - [Numpy](https://scipy-lectures.org/intro/numpy/index.html)
    - [Operations](https://scipy-lectures.org/intro/numpy/operations.html)

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

- List 와 indexing

In [3]:
A = [1, 'b', 'c']

In [4]:
B = [10,20,30,40,50,60]

In [5]:
B[2]

30

In [6]:
B[3:6]

[40, 50, 60]

In [7]:
Blist = B[3:6]
Blist

[40, 50, 60]

In [8]:
B[3:6][1]

50

In [9]:
type(B[3:6])

list

* List in List

In [10]:
B = [1, 2, 'c', [1, 3, 4]]
B

[1, 2, 'c', [1, 3, 4]]

In [11]:
type(B[3])

list

In [12]:
B[3][1]

3

In [13]:
C = [[1,2,3,4], [3,[12,4,5,65],'c', 10], 'a']

In [14]:
C[1][1][3]+10


75

### Vector의 표기 단위 차이

* 수학에서 벡터의 기본 표기 단위
    - Column (열) vector로 표기하는 것이 관습임.
    - 예제
    \begin{align*}
        x = \begin{bmatrix}
        x_1\\
        x_2\\
        x_3
        \end{bmatrix} \in \mathbb{R}^{3\times 1}
    \end{align*}
* 코딩 (Python)에서 벡터의 기본 단위
    - 다른 구조체와 메모리 구조상 Row (행) vector로 표기하는 것이 관습
    - 예
    
    
                                    `x = np.array([1, 2, 3])`

In [15]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [16]:
a = np.array([[1,2,3], [4,5,6]])

In [17]:
a[1][1]

5

#### Python에서 Matrix 생성하기

* 다음 $X\in \mathbb{R}^{2\times 3}$ 행렬을 고려합시다:
\begin{align*}
X = \begin{bmatrix}
5 & 6 & 8 \\
6 & 7 & 4 \\
\end{bmatrix}
\end{align*}

* $X$ 행렬의 각 column (열)을 $x^{(i)}\in \mathbb{R}^2$이라고 하겠습니다. 즉, 
\begin{align*}
X = \begin{bmatrix}
x^{(1)} & x^{(2)} & x^{(3)}
\end{bmatrix}
\end{align*}
과 같이 표현 됩니다. 더 자세하게 한번더 설명하자면
\begin{align*}
x^{(1)} = \begin{bmatrix}
5\\
6
\end{bmatrix}, \quad
x^{(2)} = \begin{bmatrix}
6\\
7
\end{bmatrix}, \quad
x^{(3)} = \begin{bmatrix}
8\\
4
\end{bmatrix}
\end{align*}

* list에서 생성
- indexing, slicing

In [18]:
xr1 = np.array([5, 6, 7])

In [19]:
xr1

array([5, 6, 7])

In [20]:
xr1 = np.array([[5, 6, 7]])
xr1

array([[5, 6, 7]])

In [21]:
x1 = np.array([[5], [6]])
x1

array([[5],
       [6]])

In [22]:
x1.ndim

2

In [23]:
X = np.array([[1.,2.,3.],[4.,5.,6.], [6.,7.,8.]])

In [24]:
X

array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]])

* check dimension
- `ndim`

In [25]:
a = np.array([12,3,4])

In [26]:
a.ndim

1

In [27]:
X.ndim

2

In [28]:
a = np.array([12,3,4])

In [29]:
b = np.array([[12,3,4]])

In [30]:
a.ndim

1

In [31]:
b.ndim

2

* check type
- `dtype`

In [32]:
X.dtype

dtype('float64')

In [33]:
type(X)

numpy.ndarray

#### (중요) Python에서의 Vector 

* 1-D vector
    - row vector만 표현 가능
* 2-D vector
    - row, column vector 모두 표현 가능
* 어떤 방식을 사용해야하는가?
* vector 또는 행렬에 적용하는 함수에 return 방식을 알고 있어야함!!

#### (수학) 차원 확인 명령어
- $X\in\mathbb{R}^{3\times 1}$
- `X.shape`

In [34]:
X = np.array([[1],[2],[3]])

In [35]:
X

array([[1],
       [2],
       [3]])

In [36]:
X.shape

(3, 1)

#### Matrix 연산자 I
- Transpose (전치) $X^T$
    - `x.T`
- `reshape`

In [37]:
X = np.array([[1., 2., 3.],
       [4., 5., 6.]])
X

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
X.shape

(2, 3)

In [39]:
X.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [40]:
X.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [41]:
X.reshape(6)

array([1., 2., 3., 4., 5., 6.])

In [42]:
X.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [43]:
A = X.reshape(6,1)
A

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [44]:
X

array([[1., 2., 3.],
       [4., 5., 6.]])

#### Vector transpose 주의점
- (중요) transpose 연산자는 1D array는 변환하지 못한다!

In [45]:
a = np.array([1,2,3])

In [46]:
a.T

array([1, 2, 3])

In [47]:
a.shape

(3,)

In [48]:
b = np.array([[1,2,3]])

In [49]:
b.T

array([[1],
       [2],
       [3]])

In [50]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

* 다음 두개의 $x^{(i)}\in\mathbb{R}^3$ vector를 고려합시다:
\begin{align*}
x^{(1)} = \begin{bmatrix}
5\\
6\\
7
\end{bmatrix}, \quad
x^{(2)} = \begin{bmatrix}
6\\
7\\
5
\end{bmatrix}
\end{align*}
* $X$ 행렬의 각 row (행)을 $(x^{(i)})^T\in \mathbb{R}^{1\times 3}$이라고 하겠습니다. 즉, 
\begin{align*}
X = \begin{bmatrix}
(x^{(1)})^T \\
(x^{(2)})^T \\
\end{bmatrix}
\end{align*}
과 같이 표현 됩니다. 
* 즉 $X\in \mathbb{R}^{2\times 3}$ 는 다음과 같죠:
\begin{align*}
X = \begin{bmatrix}
5 & 6 & 8 \\
6 & 7 & 4 \\
\end{bmatrix}
\end{align*}



In [51]:
x1 = np.array([[5], [6], [7]])
x2 = np.array([[6], [7], [5]])
print('x1=', x1)
print('x2=', x2)

x1= [[5]
 [6]
 [7]]
x2= [[6]
 [7]
 [5]]


In [52]:
x2.shape

(3, 1)

In [53]:
x1T = x1.T
x2T = x2.T
print('x1T=', x1T)
print('x2T=', x2T)

x1T= [[5 6 7]]
x2T= [[6 7 5]]


In [54]:
x1TT = x1.reshape(1,3)
x1TT

array([[5, 6, 7]])

* `vstack` (vertical (수직) stack (쌓다))

In [55]:
X = np.vstack([x1.T, x2.T])
X

array([[5, 6, 7],
       [6, 7, 5]])

* `hstack` (horizontal (수평) stack (쌓다))

In [56]:
Xhstack = np.hstack([x1T, x2T])
Xhstack

array([[5, 6, 7, 6, 7, 5]])

In [57]:
Xhstack2 = np.hstack([x1, x2])
Xhstack2

array([[5, 6],
       [6, 7],
       [7, 5]])

* Sequential Generation
     - `ones`
     - `zeros`
     - `arange`
     - `linspace`

In [58]:
zvec = np.zeros((1,3))
zvec

array([[0., 0., 0.]])

In [59]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
for i in np.arange(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [61]:
np.linspace(0,4,2)

array([0., 4.])

* Random Generation
- `random.rand`

In [62]:
d = 2*np.random.rand(1,10)-1
d

array([[ 0.30674891,  0.36587002,  0.38088586, -0.45338323,  0.20775052,
        -0.32592062,  0.16531729, -0.60270264, -0.93641998,  0.77168693]])

* Gaussian (Normal) random generation
    - pdf
\begin{align*}
p(x) = \frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}
\end{align*}

    - 정규분포 mean=0, variance = 1 생성 명령어
`numpy.random.randn` 


In [63]:
e = 2*np.random.randn(3,4)+2

In [64]:
e

array([[ 4.29817421, -1.79658233,  4.13343788,  2.94857947],
       [ 5.1407927 ,  4.02826057,  3.8511519 ,  1.40798477],
       [ 0.39741524,  2.80303949,  1.76184695,  2.96484245]])

* 차원축소
* `squeeze()`

In [65]:
f = np.array([[[1,2,3,4]]])

In [66]:
f.shape

(1, 1, 4)

In [67]:
f.squeeze().shape

(4,)

* Matrix multiplication
    - `matmul`
    - Generate $A\in\mathbb{R}^{3\times 2}$, $a^{(i)}\in\mathbb{R}^{3}$
        \begin{align*}
            A = \begin{bmatrix}
                a^{(1)} & a^{(2)} & a^{(3)}  
            \end{bmatrix}
        \end{align*}
        - Example, 
            \begin{align*}
            a^{(1)} = \begin{bmatrix}
                3 \\
                4 \\
                5 \\
            \end{bmatrix}
        \end{align*}
    - Generate $B\in\mathbb{R}^{3\times 4}$
        \begin{align*}
            B = \begin{bmatrix}
                b^{(1)} & b^{(2)} & b^{(3)}  & b^{(4)}  
            \end{bmatrix}
        \end{align*}
    - $(a^{(1)})^T \cdot b^{(2)}$

In [68]:
A = np.arange(0,6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [69]:
B = np.random.randn(3,4)
B

array([[-0.32600404, -0.34941023,  1.45385718,  1.36613499],
       [-2.11958601,  1.01805209, -1.39884863,  1.20090679],
       [-0.83528129, -1.10791382,  0.40456538, -0.2293917 ]])

In [70]:
A+B

ValueError: operands could not be broadcast together with shapes (3,2) (3,4) 

In [81]:
a1 = A[:, 0].reshape(3,1)
a1

array([[0],
       [2],
       [4]])

In [82]:
B

array([[-0.01035756,  0.51396541, -1.6955689 ,  0.53735338],
       [ 1.31514047,  1.12055222,  0.60079295,  0.03643204],
       [-0.11646949,  0.06500003,  0.2167659 , -1.17907693]])

In [83]:
b2 = B[:, 1].reshape(-1,1)
b2

array([[0.51396541],
       [1.12055222],
       [0.06500003]])

In [84]:
np.matmul(a1.T, b2)

array([[2.50110459]])

* Matrix operations
    - sum(axis)

In [85]:
C = np.random.randn(3,3)
C

array([[ 1.19092585,  2.55993108, -2.21536135],
       [-0.13682982,  1.38946478, -0.02025555],
       [ 0.34858958,  1.11803819, -1.39341886]])

In [86]:
D = np.random.randn(3,3)
D

array([[ 0.52969963,  2.21457986,  0.81329319],
       [ 0.2110704 , -0.5314826 , -0.06892841],
       [ 0.39818242,  0.75065558,  1.23295748]])

In [87]:
c1 = C[0,:]
d1 = D[0,:]

In [88]:
a = np.array([1,2,3,4])
b = 2*np.ones(4)
b

array([2., 2., 2., 2.])

In [89]:
a

array([1, 2, 3, 4])

In [90]:
c = a*b
c

array([2., 4., 6., 8.])

* `sum`

In [91]:
np.sum(a*b)

20.0

In [92]:
np.matmul(a, b.reshape(-1,1))

array([20.])

In [93]:
A = np.arange(3,11, 1).reshape(2,4)
A

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [94]:
c = np.sum(A, axis = 1).reshape(-1,1)
c

array([[18],
       [34]])

In [95]:
A = np.random.randn(4,3)
A

array([[-0.52156001,  0.27124676,  0.79351931],
       [-0.04577648,  1.81919622, -0.71333098],
       [ 0.75388469, -0.10114094,  0.59902164],
       [ 0.23927547, -1.5660247 ,  0.44842674]])

In [96]:
B= np.ones((4,1))
B

array([[1.],
       [1.],
       [1.],
       [1.]])

In [97]:
A+B

array([[ 0.47843999,  1.27124676,  1.79351931],
       [ 0.95422352,  2.81919622,  0.28666902],
       [ 1.75388469,  0.89885906,  1.59902164],
       [ 1.23927547, -0.5660247 ,  1.44842674]])

* Broadcasting

![This is the caption\label{mylabel}](https://scipy-lectures.org/_images/numpy_broadcasting.png)
https://scipy-lectures.org/_images/numpy_broadcasting.png