이름: 나영민

학번: 20183217

# Neural networks with PyTorch

Pytorch의 `nn.module`을 활용하여 만드는 유용한 방법을 학습합니다.

<div style="text-align:center"><img src='https://drive.google.com/uc?export=download&id=1J2SeiPpVJs1-ML2BdLrcxkGGmHpRxIVE' width="250" height="200"> 

### Lego block coding! </div>

In [2]:
import torch
import numpy as np

from torch import nn
import torch.nn.functional as F
from collections import OrderedDict

torch.manual_seed(0)

`nn.Linear`: $Z^{[\ell]} = A^{[\ell-1]}W^T+b$
연산.

해당 layer의 

- 입력 차원 `n_input=30`
- 출력 차원 `n_output=60`


In [3]:
# Example of nn.linear
linear_layer1 = nn.Linear(30, 60)

In [4]:
A = torch.randn(60, 30)
linear_layer1(A).shape

torch.Size([60, 60])

How to get the weights and bias of each `nn.Linear`

In [5]:
# Example of weights
linear_layer1.weight.data = torch.ones_like(linear_layer1.weight)

In [6]:
linear_layer1.weight 

Parameter containing:
tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]], requires_grad=True)

### NN example

- input units: 20
- hidden layer: 30, 40
- output units: 3
- activation function: ReLU
- output layer: No activation



In [7]:
# Simple NN construction

class FCN(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.lin1 = nn.Linear(20, 30)
        self.lin2 = nn.Linear(30, 40)
        self.lin3 = nn.Linear(40, 3)
        self.relu = nn.ReLU(True)
        
    def forward(self, x):
        x = self.lin1(x)
        x = self.relu(x)
        x = self.lin2(x)
        x = self.relu(x)
        x = self.lin3(x)
        return x
    


In [8]:
Xtrain = torch.randn(60, 20)

model = FCN()
model(Xtrain)

tensor([[ 0.1835,  0.0993, -0.2714],
        [ 0.3332,  0.2873, -0.3591],
        [ 0.3309,  0.2476, -0.3577],
        [ 0.1238,  0.2104, -0.2191],
        [ 0.2073,  0.1916, -0.2385],
        [ 0.2006,  0.1463, -0.2508],
        [ 0.2636,  0.2812, -0.4325],
        [ 0.2828,  0.1841, -0.2341],
        [ 0.1539,  0.2094, -0.2452],
        [ 0.0792,  0.1489, -0.1712],
        [ 0.2080,  0.2306, -0.3681],
        [ 0.2313,  0.1119, -0.3857],
        [ 0.1765,  0.1590, -0.1997],
        [ 0.3639,  0.1522, -0.2656],
        [ 0.2642,  0.1714, -0.2678],
        [ 0.2187,  0.1344, -0.1754],
        [ 0.1186,  0.1411, -0.1231],
        [ 0.2653,  0.1869, -0.3321],
        [ 0.1993,  0.1813, -0.2347],
        [ 0.2322,  0.2906, -0.4095],
        [ 0.2172,  0.0992, -0.2397],
        [ 0.2361,  0.3409, -0.4224],
        [ 0.3504,  0.3091, -0.4316],
        [ 0.1988,  0.0777, -0.2611],
        [ 0.2096,  0.2100, -0.2556],
        [ 0.1307,  0.0951, -0.1367],
        [ 0.2979,  0.2679, -0.3730],
 

In [9]:
model

FCN(
  (lin1): Linear(in_features=20, out_features=30, bias=True)
  (lin2): Linear(in_features=30, out_features=40, bias=True)
  (lin3): Linear(in_features=40, out_features=3, bias=True)
  (relu): ReLU(inplace=True)
)

In [10]:
# Example of parameters() in models
# param_iterator = model.parameters()

# for param in param_iterator:
#     print(param)


In [11]:
# nn.Sequential() example

class FCN_seq(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.fc = nn.Sequential(nn.Linear(20, 30),
                      nn.ReLU(True),
                      nn.Linear(30, 40),
                      nn.ReLU(True),
                      nn.Linear(40, 3)
        )
        
    def forward(self, x):
        return self.fc(x)
        
        
        
# self.lin1 = nn.Linear(20, 30)
# self.lin2 = nn.Linear(30, 40)
# self.lin3 = nn.Linear(40, 3)
# self.relu = nn.ReLU(True)

In [12]:
model_seq = FCN_seq()
Xtrain.shape
model_seq

FCN_seq(
  (fc): Sequential(
    (0): Linear(in_features=20, out_features=30, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=30, out_features=40, bias=True)
    (3): ReLU(inplace=True)
    (4): Linear(in_features=40, out_features=3, bias=True)
  )
)

In [13]:
model_seq.fc[0]

Linear(in_features=20, out_features=30, bias=True)

In [14]:
class FCN_seq_v2(nn.Module):
    def __init__(self):
        super().__init__()
        

        
        temp = self.fcn_block(20, 30)+self.fcn_block(30, 40)+[nn.Linear(40,1)]
        self.fc = nn.Sequential(*temp)
        
        
    def fcn_block(self, in_dim, out_dim):
        return [nn.Linear(in_dim, out_dim),
                             nn.ReLU(True)]
        
        
    def forward(self, x):
        return self.fc(x)
        
        
        
# self.lin1 = nn.Linear(20, 30)
# self.lin2 = nn.Linear(30, 40)
# self.lin3 = nn.Linear(40, 3)
# self.relu = nn.ReLU(True)

In [15]:
model_seq_v2 = FCN_seq_v2()
model_seq_v2

FCN_seq_v2(
  (fc): Sequential(
    (0): Linear(in_features=20, out_features=30, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=30, out_features=40, bias=True)
    (3): ReLU(inplace=True)
    (4): Linear(in_features=40, out_features=1, bias=True)
  )
)

In [16]:
class FCN_final(nn.Module):
    def __init__(self, in_dim, hlayer, out_dim):
        super().__init__()
        
        l_list = self.fcn_block(in_dim, hlayer[0])
        
        for l1, l2 in zip(hlayer[:-1], hlayer[1:]):
            l_list = l_list + self.fcn_block(l1, l2)
        
        l_list = l_list + [nn.Linear(hlayer[-1], out_dim)]
        
        self.fc = nn.Sequential(*l_list)
        
        
    def fcn_block(self, in_dim, out_dim):
        return [nn.Linear(in_dim, out_dim),
                             nn.ReLU(True)]
        
        
    def forward(self, x):
        return self.fc(x)
        
        

In [17]:
hlayer = [30, 40]
in_dim = 20
out_dim= 3

myfcn_final = FCN_final(in_dim, hlayer, out_dim)

In [18]:
myfcn_final

FCN_final(
  (fc): Sequential(
    (0): Linear(in_features=20, out_features=30, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=30, out_features=40, bias=True)
    (3): ReLU(inplace=True)
    (4): Linear(in_features=40, out_features=3, bias=True)
  )
)

In [19]:
# Ordered dict example
# nn.Sequential() example

class FCN_seq_ordered_dic(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.fc = nn.Sequential(OrderedDict([('lin1', nn.Linear(20, 30)),
                      ('relu1', nn.ReLU(True)),
                      ('lin2', nn.Linear(30, 40)),
                      ('relu2',nn.ReLU(True)),
                      ('lin3', nn.Linear(40, 3))
                                            ])
        )
        
    def forward(self, x):
        return self.fc(x)
        
        
        
# self.lin1 = nn.Linear(20, 30)
# self.lin2 = nn.Linear(30, 40)
# self.lin3 = nn.Linear(40, 3)
# self.relu = nn.ReLU(True)

In [20]:
# ModuleList(), ModuleDict()

In [21]:
# state_dict() example
model.state_dict()

OrderedDict([('lin1.weight',
              tensor([[ 1.1542e-01, -1.5343e-01, -1.4473e-01,  6.0137e-02,  3.4798e-02,
                       -1.9658e-01, -1.6290e-01, -1.7801e-01,  1.7759e-01,  1.4619e-01,
                       -1.1770e-01,  3.3738e-02, -5.1431e-02,  1.9439e-01, -2.0253e-01,
                       -1.6313e-01, -1.8617e-01,  1.3013e-01, -1.1178e-01,  1.3318e-01],
                      [ 7.5586e-02, -1.0930e-01, -6.0237e-02, -9.0490e-02,  9.8650e-02,
                       -8.9674e-02,  7.5885e-02,  1.5974e-02, -1.7857e-01, -1.4056e-01,
                       -1.5504e-01,  1.1717e-01,  4.8451e-02, -5.6224e-03, -1.3314e-01,
                       -2.2155e-01, -7.9131e-02, -1.7114e-01, -2.2241e-01, -2.1327e-01],
                      [-1.4606e-01, -2.1738e-01,  6.9704e-02,  8.3668e-02,  9.0129e-02,
                       -2.2260e-01,  1.3827e-01,  4.3595e-02,  1.1434e-01, -5.4957e-02,
                        1.0738e-01, -2.1207e-01,  7.6162e-02,  1.7731e-01,  9.3997e-02,
 

# Problem Setup

<div style="text-align:center"> <img src='https://drive.google.com/uc?export=download&id=1FRhniwGeeutBSJQRdW6GzshMfDrPz7oJ' width="250" height="200"> </div>
    
Build a Fully connected neural network with

- 3 layers
- 마지막 layer의 unit 수는 `1` 
  - 마지막 layer의 activation은 없음 (linear layer)
- Data feature 수는 `100`

- input unit 수는 data 크기를 보고 맞추세요
- hidden layer의 unit 수는 `[80, 50]`
  - hidden layer의 activation 함수는 ReLU

- model class 명 `myFCN`
  - instance 명 `my_model` 생성
  - `my_model` 출력

## Problem 1

problem setup에서 구성한 neural network을 `nn.Sequential`을 활용하여 생성하세요

In [22]:
## 사용할 data 
batch_size = 30
num_feature = 100

X_train = torch.randn(batch_size, num_feature)

In [23]:
X_train.shape

torch.Size([30, 100])

In [24]:
# Problem 1 코딩 (매 줄마다 주석 필수 )

class FCN_seq(nn.Module):   # nn.Module 클래스를 상속받는 FCN_seq라는 클래스를 생성
    def __init__(self): #모델을 정의
        super().__init__() #상위 클래스의 생성자를 호출해 실행
        
        #self.fc는 nn.Sequential을 사용하여 순차적으로 층을 쌓는 fully connected layer를 정의한다.
        self.fc = nn.Sequential(nn.Linear(100, 80), # 입력값이 100이며 출력값은 80인 fully connected layer
                      nn.ReLU(True), #액티베이션 함수 렐루를 적용
                      nn.Linear(80, 50), #입력값이 80이며 출력값은 50인 fully connected layer
                      nn.ReLU(True), #액티베이션 함수 렐루를 적용
                      nn.Linear(50, 1) #입력값이 50이며 출력값이 1인 fully connected layer
        )
        
    def forward(self, x): #forward 함수를 정의
        return self.fc(x) #self.fc의 값을 반환

In [34]:
my_model = FCN_seq() #FCN_seq 클래스를 my_model 변수에 할당

In [40]:
my_model #모델 확인

FCN_seq(
  (fc): Sequential(
    (lin1): Linear(in_features=100, out_features=80, bias=True)
    (relu1): ReLU(inplace=True)
    (lin2): Linear(in_features=80, out_features=50, bias=True)
    (relu2): ReLU(inplace=True)
    (lin3): Linear(in_features=50, out_features=1, bias=True)
  )
)

In [46]:
print(my_model(X_train)) #결과 확인
print(my_model(X_train).shape) #모양 확인

tensor([[-0.0397],
        [-0.0058],
        [ 0.0512],
        [-0.1175],
        [ 0.0493],
        [-0.0498],
        [-0.0433],
        [-0.1607],
        [-0.0062],
        [-0.1179],
        [-0.1638],
        [-0.0805],
        [-0.1165],
        [ 0.0313],
        [-0.0355],
        [-0.1519],
        [-0.1232],
        [-0.1027],
        [-0.1303],
        [-0.1960],
        [-0.1431],
        [-0.1537],
        [-0.0523],
        [-0.1395],
        [-0.1408],
        [-0.3325],
        [ 0.0091],
        [-0.0982],
        [-0.0588],
        [-0.0658]], grad_fn=<AddmmBackward0>)
torch.Size([30, 1])


## Problem 2

problem setup에서 구성한 neural network을 `OrderedDict`을 활용하여 생성하세요
- 각 layer의 이름을 주고 생성하세요

In [ ]:
# 답작성

In [51]:
class FCN_seq(nn.Module): # nn.Module 클래스를 상속받는 FCN_seq라는 클래스를 생성
    def __init__(self):       #모델을 정의
        super().__init__()     #상위 클래스의 생성자를 호출해 실행
        
        #self.fc는 nn.Sequential을 사용하여 순차적으로 층을 쌓는 fully connected layer를 정의한다. 이때 ordereddict 기능을 활용해 각 층의 이름을 설정한다.
        self.fc = nn.Sequential(OrderedDict([('lin1', nn.Linear(100, 80)),  # 층이름 lin1: 입력값이 100이며 출력값은 80인 fully connected layer
                      ('relu1', nn.ReLU(True)), # 층이름 relu1: 액티베이션 함수 렐루를 적용
                      ('lin2', nn.Linear(80, 50)), # 층이름 lin2: 입력값이 80이며 출력값은 50인 fully connected layer
                      ('relu2',nn.ReLU(True)), # 층이름 relu2: 액티베이션 함수 렐루를 적용
                      ('lin3', nn.Linear(50, 1)) # 층이름 lin3: 입력값이 50이며 출력값은 1인 fully connected layer
                                            ])
        )
        
    def forward(self, x): #forward 함수를 정의
        return self.fc(x) #self.fc의 값을 반환

In [52]:
my_model = FCN_seq() #FCN_seq 클래스를 my_model 변수에 할당

In [53]:
my_model #모델 확인

FCN_seq(
  (fc): Sequential(
    (lin1): Linear(in_features=100, out_features=80, bias=True)
    (relu1): ReLU(inplace=True)
    (lin2): Linear(in_features=80, out_features=50, bias=True)
    (relu2): ReLU(inplace=True)
    (lin3): Linear(in_features=50, out_features=1, bias=True)
  )
)

In [54]:
print(my_model(X_train)) #결과 확인
print(my_model(X_train).shape) #모양 확인

tensor([[ 0.0427],
        [ 0.0033],
        [ 0.0881],
        [-0.0857],
        [-0.0552],
        [-0.0710],
        [ 0.0203],
        [-0.0425],
        [ 0.0599],
        [ 0.0232],
        [-0.0106],
        [-0.0256],
        [-0.1325],
        [-0.1137],
        [ 0.0244],
        [-0.2331],
        [ 0.0083],
        [ 0.0401],
        [-0.0459],
        [ 0.1170],
        [-0.0259],
        [ 0.0143],
        [ 0.0434],
        [-0.0509],
        [-0.0328],
        [ 0.1981],
        [ 0.0574],
        [-0.0716],
        [-0.0311],
        [ 0.1015]], grad_fn=<AddmmBackward0>)
torch.Size([30, 1])
